# Notebook 04

# Extração de Características utilizando Composition of k-Spaced Amino Acid Pairs (CKSNAP)

No notebook anterior foi implementado o descritor Amino Acid Linking (AAL), responsável por representar cada sequência por meio da frequência dos pares consecutivos de aminoácidos.

Embora essa abordagem preserve parte da ordem dos resíduos, ela considera apenas aminoácidos adjacentes na sequência.

Entretanto, em proteínas e peptídeos, resíduos separados por alguns aminoácidos podem participar conjuntamente da formação da estrutura tridimensional e influenciar diretamente processos de reconhecimento molecular.

Para incorporar essa informação, neste notebook será implementado o descritor CKSNAP (Composition of k-Spaced Amino Acid Pairs), que contabiliza pares separados por diferentes distâncias ao longo da sequência.

## Objetivos

Ao final deste notebook será possível:

- compreender o descritor CKSNAP;

- implementar o algoritmo do zero;

- gerar descritores para diferentes valores de k;

- analisar o impacto do aumento da distância entre resíduos;

- comparar CKSNAP com AAC e AAL.

## Por que o AAL ainda é limitado?

Considere a sequência

```
A G P L K T
```

O descritor AAL considera apenas

```
AG

GP

PL

LK

KT
```

Entretanto,

os pares

```
AP

GL

PK

LT
```

também carregam informação importante.

Da mesma forma,

```
AL

GK

PT
```

podem participar da formação de estruturas secundárias.

O descritor CKSNAP captura exatamente esse tipo de relação.

## Composition of k-Spaced Amino Acid Pairs

Para cada valor de k, o algoritmo contabiliza pares de aminoácidos separados exatamente por k resíduos.

Quando

k=0

obtém-se exatamente os pares consecutivos utilizados pelo descritor AAL.

Quando

k=1

há um aminoácido entre os dois resíduos.

Quando

k=2

existem dois resíduos intermediários.

...

Neste trabalho será utilizado

```
k = 0,1,2,3,4,5
```

como definido pelo framework SAGAPEP.

Considere uma sequência contendo N aminoácidos.

Para um determinado valor de k,

existem

\[
N-k-1
\]

pares possíveis.

A frequência relativa do par

ij

é dada por

\[
CKSNAP_{ij}^{(k)}
=
\frac{n_{ij}^{(k)}}
{N-k-1}
\]

onde

- \(n_{ij}^{(k)}\) representa o número de ocorrências do par separado por distância \(k\);

- \(N-k-1\) representa o número total de pares possíveis para essa distância.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter

In [2]:
df = pd.read_csv("../data/raw/sagapep.csv")
df.head(10)

                           peptide_fasta_sequence  best_docking_score
0                                       RFGYGYGPY            -230.308
1                    PAAAPPTLPPYFMKGSIIQLANGELKKV            -227.293
2                         SIPPCPQTWRSLWIGYSFLMHTG            -224.630
3                                    RIGRFGYGYGPY            -218.979
4                                     PGPRYQPFRLT            -218.227
5                          WAFTPLHEAAQKGRTQLCALLL            -214.970
6                    PGPSSPYIPSPGGAMSPSYSPTSPAYEP            -210.899
7                        SRGPPPRATRLPPPGPLCSSFSTP            -210.009
8                                      GRFGYGYGPY            -209.840
9  PRGPAGPSGPAGKDGRTGHPGTVGPAGIRGPQGHQGPAGPPGPPGP            -209.592

In [3]:
from itertools import product

AA = [
"A","C","D","E","F",
"G","H","I","K","L",
"M","N","P","Q","R",
"S","T","V","W","Y"
]

pairs = [
    a+b
    for a,b in product(AA,AA)
]

In [ ]:
# Implementação do algoritmo
from collections import Counter

def cksnap(sequence, k):
    seq = sequence.upper()
    links = []
    for i in range(len(seq)-k-1):
        links.append(
            seq[i] +
            seq[i+k+1]
        )

    total = len(links)
    counts = Counter(links)
    vector = {}

    for p in pairs:
        if total == 0:
            vector[p]=0
        else:
            vector[p]=counts.get(p,0)/total
    return vector

In [5]:
cksnap("AGPLKT",0)

{'AA': 0.0,
 'AC': 0.0,
 'AD': 0.0,
 'AE': 0.0,
 'AF': 0.0,
 'AG': 0.2,
 'AH': 0.0,
 'AI': 0.0,
 'AK': 0.0,
 'AL': 0.0,
 'AM': 0.0,
 'AN': 0.0,
 'AP': 0.0,
 'AQ': 0.0,
 'AR': 0.0,
 'AS': 0.0,
 'AT': 0.0,
 'AV': 0.0,
 'AW': 0.0,
 'AY': 0.0,
 'CA': 0.0,
 'CC': 0.0,
 'CD': 0.0,
 'CE': 0.0,
 'CF': 0.0,
 'CG': 0.0,
 'CH': 0.0,
 'CI': 0.0,
 'CK': 0.0,
 'CL': 0.0,
 'CM': 0.0,
 'CN': 0.0,
 'CP': 0.0,
 'CQ': 0.0,
 'CR': 0.0,
 'CS': 0.0,
 'CT': 0.0,
 'CV': 0.0,
 'CW': 0.0,
 'CY': 0.0,
 'DA': 0.0,
 'DC': 0.0,
 'DD': 0.0,
 'DE': 0.0,
 'DF': 0.0,
 'DG': 0.0,
 'DH': 0.0,
 'DI': 0.0,
 'DK': 0.0,
 'DL': 0.0,
 'DM': 0.0,
 'DN': 0.0,
 'DP': 0.0,
 'DQ': 0.0,
 'DR': 0.0,
 'DS': 0.0,
 'DT': 0.0,
 'DV': 0.0,
 'DW': 0.0,
 'DY': 0.0,
 'EA': 0.0,
 'EC': 0.0,
 'ED': 0.0,
 'EE': 0.0,
 'EF': 0.0,
 'EG': 0.0,
 'EH': 0.0,
 'EI': 0.0,
 'EK': 0.0,
 'EL': 0.0,
 'EM': 0.0,
 'EN': 0.0,
 'EP': 0.0,
 'EQ': 0.0,
 'ER': 0.0,
 'ES': 0.0,
 'ET': 0.0,
 'EV': 0.0,
 'EW': 0.0,
 'EY': 0.0,
 'FA': 0.0,
 'FC': 0.0,
 'FD': 0.0,
 'FE': 0.0,
 'FF': 0.0,
 'FG': 0.0,
 'FH': 0.0,
 'FI': 0.0,
 'FK': 0.0,
 'FL': 0.0,
 'FM': 0.0,
 'FN': 0.0,
 'FP': 0.0,
 'FQ': 0.0,
 'FR': 0.0,
 'FS': 0.0,
 'FT': 0.0,
 'FV': 0.0,
 'FW': 0.0,
 'FY': 0.0,
 'GA': 0.0,
 'GC': 0.0,
 'GD': 0.0,
 'GE': 0.0,
 'GF': 0.0,
 'GG': 0.0,
 'GH': 0.0,
 'GI': 0.0,
 'GK': 0.0,
 'GL': 0.0,
 'GM': 0.0,
 'GN': 0.0,
 'GP': 0.2,
 'GQ': 0.0,
 'GR': 0.0,
 'GS': 0.0,
 'GT': 0.0,
 'GV': 0.0,
 'GW': 0.0,
 'GY': 0.0,
 'HA': 0.0,
 'HC': 0.0,
 'HD': 0.0,
 'HE': 0.0,
 'HF': 0.0,
 'HG': 0.0,
 'HH': 0.0,
 'HI': 0.0,
 'HK': 0.0,
 'HL': 0.0,
 'HM': 0.0,
 'HN': 0.0,
 'HP': 0.0,
 'HQ': 0.0,
 'HR': 0.0,
 'HS': 0.0,
 'HT': 0.0,
 'HV': 0.0,
 'HW': 0.0,
 'HY': 0.0,
 'IA': 0.0,
 'IC': 0.0,
 'ID': 0.0,
 'IE': 0.0,
 'IF': 0.0,
 'IG': 0.0,
 'IH': 0.0,
 'II': 0.0,
 'IK': 0.0,
 'IL': 0.0,
 'IM': 0.0,
 'IN': 0.0,
 'IP': 0.0,
 'IQ': 0.0,
 'IR': 0.0,
 'IS': 0.0,
 'IT': 0.0,
 'IV': 0.0,
 'IW': 0.0,
 'IY': 0.0,
 'KA': 0.0,
 'KC': 0.0,
 'KD': 0.0,
 'KE': 0.0,
 'KF': 0.0,
 'KG': 0.0,
 'KH': 0.0,
 'KI': 0.0,
 'KK': 0.0,
 'KL': 0.0,
 'KM': 0.0,
 'KN': 0.0,
 'KP': 0.0,
 'KQ': 0.0,
 'KR': 0.0,
 'KS': 0.0,
 'KT': 0.2,
 'KV': 0.0,
 'KW': 0.0,
 'KY': 0.0,
 'LA': 0.0,
 'LC': 0.0,
 'LD': 0.0,
 'LE': 0.0,
 'LF': 0.0,
 'LG': 0.0,
 'LH': 0.0,
 'LI': 0.0,
 'LK': 0.2,
 'LL': 0.0,
 'LM': 0.0,
 'LN': 0.0,
 'LP': 0.0,
 'LQ': 0.0,
 'LR': 0.0,
 'LS': 0.0,
 'LT': 0.0,
 'LV': 0.0,
 'LW': 0.0,
 'LY': 0.0,
 'MA': 0.0,
 'MC': 0.0,
 'MD': 0.0,
 'ME': 0.0,
 'MF': 0.0,
 'MG': 0.0,
 'MH': 0.0,
 'MI': 0.0,
 'MK': 0.0,
 'ML': 0.0,
 'MM': 0.0,
 'MN': 0.0,
 'MP': 0.0,
 'MQ': 0.0,
 'MR': 0.0,
 'MS': 0.0,
 'MT': 0.0,
 'MV': 0.0,
 'MW': 0.0,
 'MY': 0.0,
 'NA': 0.0,
 'NC': 0.0,
 'ND': 0.0,
 'NE': 0.0,
 'NF': 0.0,
 'NG': 0.0,
 'NH': 0.0,
 'NI': 0.0,
 'NK': 0.0,
 'NL': 0.0,
 'NM': 0.0,
 'NN': 0.0,
 'NP': 0.0,
 'NQ': 0.0,
 'NR': 0.0,
 'NS': 0.0,
 'NT': 0.0,
 'NV': 0.0,
 'NW': 0.0,
 'NY': 0.0,
 'PA': 0.0,
 'PC': 0.0,
 'PD': 0.0,
 'PE': 0.0,
 'PF': 0.0,
 'PG': 0.0,
 'PH': 0.0,
 'PI': 0.0,
 'PK': 0.0,
 'PL': 0.2,
 'PM': 0.0,
 'PN': 0.0,
 'PP': 0.0,
 'PQ': 0.0,
 'PR': 0.0,
 'PS': 0.0,
 'PT': 0.0,
 'PV': 0.0,
 'PW': 0.0,
 'PY': 0.0,
 'QA': 0.0,
 'QC': 0.0,
 'QD': 0.0,
 'QE': 0.0,
 'QF': 0.0,
 'QG': 0.0,
 'QH': 0.0,
 'QI': 0.0,
 'QK': 0.0,
 'QL': 0.0,
 'QM': 0.0,
 'QN': 0.0,
 'QP': 0.0,
 'QQ': 0.0,
 'QR': 0.0,
 'QS': 0.0,
 'QT': 0.0,
 'QV': 0.0,
 'QW': 0.0,
 'QY': 0.0,
 'RA': 0.0,
 'RC': 0.0,
 'RD': 0.0,
 'RE': 0.0,
 'RF': 0.0,
 'RG': 0.0,
 'RH': 0.0,
 'RI': 0.0,
 'RK': 0.0,
 'RL': 0.0,
 'RM': 0.0,
 'RN': 0.0,
 'RP': 0.0,
 'RQ': 0.0,
 'RR': 0.0,
 'RS': 0.0,
 'RT': 0.0,
 'RV': 0.0,
 'RW': 0.0,
 'RY': 0.0,
 'SA': 0.0,
 'SC': 0.0,
 'SD': 0.0,
 'SE': 0.0,
 'SF': 0.0,
 'SG': 0.0,
 'SH': 0.0,
 'SI': 0.0,
 'SK': 0.0,
 'SL': 0.0,
 'SM': 0.0,
 'SN': 0.0,
 'SP': 0.0,
 'SQ': 0.0,
 'SR': 0.0,
 'SS': 0.0,
 'ST': 0.0,
 'SV': 0.0,
 'SW': 0.0,
 'SY': 0.0,
 'TA': 0.0,
 'TC': 0.0,
 'TD': 0.0,
 'TE': 0.0,
 'TF': 0.0,
 'TG': 0.0,
 'TH': 0.0,
 'TI': 0.0,
 'TK': 0.0,
 'TL': 0.0,
 'TM': 0.0,
 'TN': 0.0,
 'TP': 0.0,
 'TQ': 0.0,
 'TR': 0.0,
 'TS': 0.0,
 'TT': 0.0,
 'TV': 0.0,
 'TW': 0.0,
 'TY': 0.0,
 'VA': 0.0,
 'VC': 0.0,
 'VD': 0.0,
 'VE': 0.0,
 'VF': 0.0,
 'VG': 0.0,
 'VH': 0.0,
 'VI': 0.0,
 'VK': 0.0,
 'VL': 0.0,
 'VM': 0.0,
 'VN': 0.0,
 'VP': 0.0,
 'VQ': 0.0,
 'VR': 0.0,
 'VS': 0.0,
 'VT': 0.0,
 'VV': 0.0,
 'VW': 0.0,
 'VY': 0.0,
 'WA': 0.0,
 'WC': 0.0,
 'WD': 0.0,
 'WE': 0.0,
 'WF': 0.0,
 'WG': 0.0,
 'WH': 0.0,
 'WI': 0.0,
 'WK': 0.0,
 'WL': 0.0,
 'WM': 0.0,
 'WN': 0.0,
 'WP': 0.0,
 'WQ': 0.0,
 'WR': 0.0,
 'WS': 0.0,
 'WT': 0.0,
 'WV': 0.0,
 'WW': 0.0,
 'WY': 0.0,
 'YA': 0.0,
 'YC': 0.0,
 'YD': 0.0,
 'YE': 0.0,
 'YF': 0.0,
 'YG': 0.0,
 'YH': 0.0,
 'YI': 0.0,
 'YK': 0.0,
 'YL': 0.0,
 'YM': 0.0,
 'YN': 0.0,
 'YP': 0.0,
 'YQ': 0.0,
 'YR': 0.0,
 'YS': 0.0,
 'YT': 0.0,
 'YV': 0.0,
 'YW': 0.0,
 'YY': 0.0}

In [7]:
sum(
    cksnap(
        "AGPLKT",
        2
    ).values()
)

1.0

In [8]:
# Construindo o Dataset
dfs = []

for k in range(6):
    temp = (
        df["peptide_fasta_sequence"]
        .apply(
            lambda x: cksnap(x,k)
        )
        .apply(pd.Series)
    )

    temp.columns = [
        f"{c}_k{k}"
        for c in temp.columns
    ]

    dfs.append(temp)

In [11]:
cksnap_df = pd.concat(
    dfs,
    axis=1
)

cksnap_df[
    "best_docking_score"
] = df[
    "best_docking_score"
]

cksnap_df.head()

,AA_k0,AC_k0,AD_k0,AE_k0,AF_k0,AG_k0,AH_k0,AI_k0,AK_k0,AL_k0,...,YN_k5,YP_k5,YQ_k5,YR_k5,YS_k5,YT_k5,YV_k5,YW_k5,YY_k5,best_docking_score
0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,-230.308
1,0.074074,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,-227.293
2,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.058824,0.0,0.0,0.0,-224.630
3,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,-218.979
4,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.200000,0.0,0.0,0.0,-218.227